# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# show_downloads: true
title: Heartsuit's Simple Blog
email: nxq0108@126.com

description: > # this means to ignore newlines until "baseurl:"
  A place to hold mainly reading notes, and some technical stuff occasionally.
  这里主要是一些读书笔记、感悟；还有部分技术相关的内容。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username: heartsuit

# Build settings
# highlighter: pygments
markdown: kramdown # rdiscount
kramdown:
  input: GFM
theme: jekyll-theme-midnight
repository: heartsuit/heartsuit.github.io
# gems:
#   - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Social account
# twitter:  username
# weibo:    ID
# github: heartsuit
# codepen:  username
# dribbble: username

# Comment
# disqus_shortname: heartsuit
valine:
  enable: true
  appid: PBIPk11qixwpfuuoLNjNyihW-gzGzoHsz # your leancloud app id
  appkey: j48t7uK7FlIFY0W8qW03jrPV # your leancloud app key
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: 请在此处留言…… # comment box placeholder
  avatar: monsterid # gravatar style
  guest_info: 昵称,邮件,网址 # custom comment header
  pageSize: 10 # pagination size
  # path: window.location.pathname

# Google Analytics
# google_analytics: UA-64529473-1
analytics:
  baidu:
    siteid: xxxxxxxxxxxxxxxx # 百度统计 js 代码后的字符串
